<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{b429125e-3b4d-48ba-ac23-7b0d09072c1b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Controller: FB_Controller;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Controller();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>