<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{c92b9105-0189-4ab8-bb90-5be8fb337865}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
Coordinador : FB_Coordinador_ST;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Coordinador();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>